% "main.m" contains all the codes used to generate all figures used in
% the paper and in the supplemental materials.

%% Non-linear optimization for one individual 3 by running the script Optimization_over_an_individual
run_optimization_over_an_individual

%% Calibration_of_the_model_Thai_children is used to generate the phase 
% diagram of f and numLayer_max. You don't have to run because all results
% generated by the script "Calibration_of_the_model_Thai_children" is
% already saved in the 'Calibration_of_the_model.mat'. Therefore
% generating figures just requires running the script 
% "Analysis_of_calibration_of_the_model_Thai_children"

% run_calibration_of_the_model_Thai_children
Analysis_of_calibration_of_the_model_Thai_children

%% HMP_prediction is used to generate the model predictions
% Analysis_of_HMP_prediction is used to generate the plots in the paper

% run_HMP_prediction
Analysis_of_HMP_prediction


%% Variation of uptake rates and leakage fractions

% run_deviation_100_randomized_results
Analysis_100_randomized_results